config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resource :profile, only: :show

  namespace 'my' do
    resource :posts, only: :show
  end

  resources :posts, except: :index do
    scope module: :posts do
      resources :likes, only: %i[create destroy]
      resources :comments, only: :create
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :restrict_with_exception

  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts
  belongs_to :category
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy

  validates :title, :body, presence: true
  validates :body, length: { minimum: 50 }

  scope :by_recently_created, -> { order(created_at: :desc) }

  def find_like(user)
    likes.find { |like| like.user_id == user.id }
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_ancestry ancestry_column: :ancestry

  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :restrict_with_exception, inverse_of: :creator
  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy

  devise :database_authenticatable,
         :registerable,
         :rememberable,
         :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @posts = Post.includes(:creator).by_recently_created
  end
end

app/controllers/my/posts_controller.rb
# frozen_string_literal: true

class My::PostsController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @posts = current_user.posts
  end
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

module Posts
  class ApplicationController < ApplicationController
    def resource_post
      @resource_post ||= Post.find params[:post_id]
    end
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      @comment = resource_post.comments.build comment_params
      @comment.user = current_user

      if @comment.save
        redirect_to resource_post, notice: t('controllers.posts.comments.actions.update.notifications.success')
      else
        flash[:alert] = "#{t('controllers.posts.comments.actions.updated.notifications.failure_text')} #{@comment.errors.messages[:content].first}"

        redirect_to resource_post, status: :unprocessable_entity
      end
    end

    private

    def comment_params
      params.required(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!

    def create
      PostLike.find_or_create_by(
        post: resource_post,
        user: current_user
      )

      redirect_to resource_post
    end

    def destroy
      @like = resource_post.find_like current_user

      return if @like.blank?

      @like.destroy

      redirect_to resource_post
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @post = find_post
    @user_like = @post.find_like(current_user) if current_user

    @comments = @post.comments.includes(:user).arrange
    @new_comment = PostComment.new
  end

  def new
    @post = Post.new
  end

  def edit
    @post = find_post
  end

  def create
    @post = current_user.posts.build post_params

    if @post.save
      redirect_to root_path, notice: t('controllers.posts.actions.create.notifications.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = find_post

    if @post.update post_params
      redirect_to post_path, notice: t('controllers.posts.actions.update.notifications.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = find_post

    if post.delete
      redirect_to my_posts_path, notice: t('controllers.posts.actions.destroy.notifications.success')
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def find_post
    Post.find params[:id]
  end

  def post_params
    params.required(:post).permit(:title, :body, :category_id)
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active?(path)
    request.path == path
  end
end

app/views/home/index.html.slim
h1 = t(:welcome_title, scope: 'pages.home.index')

div
  - @posts.each do |post|
    article.card.mb-3
      .card-body
        h2.h5
          = link_to post.title,
            post,
            class: 'link-dark text-decoration-none'
        p.mb-2 = post.body.truncate_words 30

        .small.text-muted
          span.me-2 = t(:text, scope: 'pages.posts.likes', count: post.likes.size)
          span.me-2 = time_ago_in_words post.created_at
          span = post.creator.email

app/views/layouts/_flash.html.slim
- alert_types = { \
  notice: 'alert-info',
  alert: 'alert-danger' \
}

- flash.each do |type, message|
  div class="alert #{alert_types.fetch(type.to_sym, "alert-#{type}")}"
    = message

app/views/layouts/_posts.html.slim
div
  - posts.each do |post|
    article.card.mb-3
      .card-body
        h2.h5
          = link_to post.title,
            post,
            class: 'link-dark text-decoration-none'
        p.mb-2 = post.body.truncate_words 30

        .small.text-muted
          span.me-2 = t('views.posts.show.likes_count', count: post.likes.size)
          span.me-2 = time_ago_in_words post.created_at
          span = post.creator.email

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('views.application.title')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body.d-flex.flex-column.h-100
    header.mb-2
      .container
        = render 'layouts/navigation/menu'
    main.my-4
      .container
        = render 'layouts/flash'
        = yield

app/views/layouts/navigation/_link.html.slim
- default_params = { class: %w[nav-link link-dark] }
- link_method ||= nil

- if active?(path)
  = link_to text,
    path,
    **default_params.merge({ \
      class: %w[nav-link active] \
    })

- elsif link_method
  - if link_method == :delete
    = link_to text,
      path,
      **default_params.merge({ \
        method: :delete, \
        data: { \
          turbo_method: :delete \
        } \
      })
  - else
    = link_to text,
      path,
      **default_params.merge({ \
        method: link_method \
      })

- else
  = link_to text, path, **default_params

app/views/layouts/navigation/_menu.html.slim
nav class='navbar justify-content-end py-3 border-bottom'
  ul.nav.nav-pills
    - if current_user.present?
      li.nav-item.ms-2
        = render 'layouts/navigation/link',
          text: t('views.layouts.navigation.links.new_post'),
          path: new_post_path
      li.nav-item.ms-2
        = render 'layouts/navigation/link',
          text: t('views.layouts.navigation.links.my_posts'),
          path: my_posts_path
      li.nav-item.ms-2
        = render 'layouts/navigation/link',
          text: t('views.layouts.navigation.links.profile'),
          path: profile_path
      li.nav-item.ms-2
        = render 'layouts/navigation/link',
          text: t('views.layouts.navigation.links.sign_out'),
          path: destroy_user_session_path,
          link_method: :delete

    - else
      li.nav-item.ms-2
        = render 'layouts/navigation/link',
          text: t('views.layouts.navigation.links.sign_in'),
          path: new_user_session_path
      li.nav-item.ms-2
        = render 'layouts/navigation/link',
          text: t('views.layouts.navigation.links.sign_up'),
          path: new_user_registration_path

app/views/my/posts/show.html.slim
h1 = t('views.my.posts.title')

= render 'layouts/posts', posts: @posts

app/views/posts/_form.html.slim
= simple_form_for post, data: { turbo: false } do |f|
  = f.input :title
  = f.input :body, input_html: { style: 'min-height: 150px;' }
  = f.association :category

  = f.button :submit, t('simple_form.submit_buttons.post.edit'), class: 'btn-primary'

app/views/posts/comments/_form.html.slim
= simple_form_for comment, url:, html: { class: custom_class } do |f|
  = f.input :parent_id, as: :hidden
  = f.input :content, label: false

  = f.button :submit, t('simple_form.submit_buttons.post.comment.new'), class: 'btn-primary'

app/views/posts/comments/_nested_comment.html.slim
- nested_comments.each do |comment, deep_nested_comments|
  .pb-2 class=(comment.depth == 1 ? 'small' : 'ms-4')
    hr.mb-2
    .mb-4
      span.me-1 = comment.user.email
      span.text-muted = time_ago_in_words comment.created_at
      p = comment.content

    hr.mb-2
    = render 'posts/comments/reply_button', comment:

    = render('posts/comments/nested_comment', nested_comments: deep_nested_comments)

app/views/posts/comments/_reply_button.html.slim
- custom_class ||= ''

div class=custom_class
  - comment_id = comment.id

  a.small.text-muted data-bs-toggle='collapse' href="#new_post_comment-#{comment_id}"
    = t('views.general.buttons.reply')

  .collapse data-bs-target="new_post_comment-#{comment_id}" id="new_post_comment-#{comment_id}"
    - if current_user.present?
      = render( \
        'posts/comments/form',
        comment: comment.children.new,
        url: post_comments_path(comment.post),
        custom_class: 'mb-4' \
      )
    - else
      span
        => t('views.posts.show.comments.reply_buttons.unauthorized.text')
        = link_to t('views.posts.show.comments.reply_buttons.unauthorized.link_text'), new_user_session_path

app/views/posts/edit.html.slim
h1.h2.mb-4 = t('views.posts.edit.title')

= render 'posts/form', post: @post

app/views/posts/likes/_button.html.slim
span.me-2 = post.likes.size

- if like.present?
  = link_to post_like_path(post, like, format: :html),
    method: :delete,
    data: { turbo_method: :delete } \
    do
      i.bi.bi-hand-thumbs-up-fill
- else
  = link_to post_likes_path(post, format: :html),
    method: :post,
    data: { turbo_method: :post } \
    do
      i.bi.bi-hand-thumbs-up

app/views/posts/new.html.slim
h1.h2.mb-4 = t('views.posts.new.title')

= render 'posts/form', post: @post

app/views/posts/show.html.slim
ol.breadcrumb
  li.breadcrumb-item = link_to t('views.posts.show.tags_root'), root_path
  li.breadcrumb-item.active
    = @post.category.name

- if @post.creator == current_user
  .d-flex.gap-2
    = link_to t('views.posts.show.links.edit'), edit_post_url(@post), class: 'btn btn-primary'
    = link_to t('views.posts.show.links.destroy'),
              post_url(@post),
              method: :delete,
              data: { turbo_method: :delete },
              class: 'btn btn-danger'

article.mt-4
  h1.me-4 = @post.title

  = simple_format @post.body

  div class='d-flex justify-content-between mt-5'
    div
      span.me-2 = @post.creator.email
      span = time_ago_in_words @post.created_at
    div = render 'posts/likes/button', post: @post, like: @user_like

div
  p.lead.mb-3 = t('views.posts.show.comments.title')

  - if current_user.present?
    = render( \
      'posts/comments/form',
      comment: @new_comment,
      url: post_comments_path(@post),
      custom_class: 'mb-4' \
    )

  - @comments.each do |comment, nested_comments|
    .card.mb-4
      .card-header.mb-2.small
        span.me-2 = comment.user.email
        span = time_ago_in_words comment.created_at

      .card-body
        p.mb-3 = comment.content
        = render('posts/comments/nested_comment', nested_comments:)

      hr.my-2
      = render 'posts/comments/reply_button', comment:, custom_class: 'p-4 pb-2'

app/views/profiles/show.html.slim
h1.h2.mb-4 = t('views.profile.show.title')

p
  b Email:
  span = current_user.email
  br
  b = "#{t('views.profile.show.created_at')}: "
  span = current_user.created_at.to_date.strftime('%d.%m.%Y')

.d-flex.gap-2
  = link_to t('views.profile.show.links.edit'),
            edit_user_registration_path,
            class: 'btn border border-2 d-block'
  = link_to t('views.profile.show.links.destroy'),
            user_registration_path,
            method: :delete,
            class: 'btn btn-danger ml-2 d-block'